version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: webchat-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webchat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webchat-network

  redis:
    image: redis:7-alpine
    container_name: webchat-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - webchat-network

volumes:
  postgres_data:
  redis_data:

networks:
  webchat-network:
    driver: bridge